### ISSUE TITLE
npm install : fatal error: zmq.h: No such file or directory

### ISSUE THREAD

**Issue by y12studio** [lwmqn/lwmqn-demo#1]
hi, unble to run npm install successfully.

### System information
```
$ npm version
{ 'lwmqn-demo': '0.3.0',
  npm: '3.10.8',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '56.1',
  modules: '48',
  node: '6.9.1',
  openssl: '1.0.2j',
  uv: '1.9.1',
  v8: '5.1.281.84',
  zlib: '1.2.8' }
```
### Expected behaviour
```
$ npm install 
successfully 
```
### Actual behaviour
```
$ npm install

> zmq@2.15.3 install /home/lin/git/lwmqn-demo/node_modules/zmq
> node-gyp rebuild

make: Entering directory `/home/lin/git/lwmqn-demo/node_modules/zmq/build'
  CXX(target) Release/obj.target/zmq/binding.o
../binding.cc:28:17: fatal error: zmq.h: No such file or directory
 #include <zmq.h>
                 ^
compilation terminated.
make: *** [Release/obj.target/zmq/binding.o] Error 1
make: Leaving directory `/home/lin/git/lwmqn-demo/node_modules/zmq/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.13.0-100-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/lin/git/lwmqn-demo/node_modules/zmq
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: zmq@2.15.3 (node_modules/zmq):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: zmq@2.15.3 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
```
### Steps to reproduce the behaviour
```
$ git clone https://github.com/lwmqn/lwmqn-demo  
$ cd lwmqn-demo  && npm install  
```

**Comment by simenkid** [comment]
Hello @y12studio. zmq is not a necessity, that's okay to ignore the error.
