### ISSUE TITLE
Start error TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by hbrks** [lwmqn/lwmqn-demo#2]
lwmqn-demo/node_modules/mqtt-node/lib/init.js:189
                qn.mac = info.mac_address.toLowerCase();
                                          ^

TypeError: Cannot read property 'toLowerCase' of undefined
    at /home/hbrks/DEV/lwmqn-demo/node_modules/mqtt-node/lib/init.js:189:43
    at /home/hbrks/DEV/lwmqn-demo/node_modules/network/lib/index.js:113:11
    at ChildProcess.exithandler (child_process.js:265:7)
    at ChildProcess.emit (events.js:180:13)
    at maybeClose (internal/child_process.js:936:16)
    at Socket.stream.socket.on (internal/child_process.js:353:11)
    at Socket.emit (events.js:180:13)
    at Pipe._handle.close [as _onclose] (net.js:541:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lwmqn-demo@0.4.0 start: `cross-env NODE_ENV=production node main`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lwmqn-demo@0.4.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hbrks/.npm/_logs/2019-01-28T11_57_13_055Z-debug.log

[2019-01-28T11_57_13_055Z-debug.log](https://github.com/lwmqn/lwmqn-demo/files/2802818/2019-01-28T11_57_13_055Z-debug.log)

**Comment by amer8** [comment]
@hbrks thanks for the error report. we have to update the dependency `mqtt-shepherd` first, as its build is broken on 9.x and later..
Until then you can run `lwmqn-demo` on `8.x` without problems.
